site_name: Simple Model
site_description: "'simple_model' is a template module for python AI/ML model."
site_url: https://bybatkhuu.github.io/model.python-template
repo_name: bybatkhuu/model.python-template
repo_url: https://github.com/bybatkhuu/model.python-template
theme:
  name: material
  # name: readthedocs
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    # - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme)"
      primary: black
      accent: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - mkdocstrings
  - blog:
      blog_dir: pages/blog
      post_date_format: medium
      archive_date_format: yyyy/MM
      archive_url_date_format: yyyy/MM
      blog_toc: true
nav:
  - Home:
      - README.md
  - Getting Started:
      # - pages/getting-started/README.md
      - Prerequisites: pages/getting-started/prerequisites.md
      - Installation: pages/getting-started/installation.md
      - Configuration: pages/getting-started/configuration.md
      - Examples: pages/getting-started/examples.md
      - Error codes: pages/getting-started/error-codes.md
  - API Documentation:
      # - pages/api-docs/README.md
      - SimpleModel: pages/api-docs/SimpleModel.md
      - ModelConfigPM: pages/api-docs/ModelConfigPM.md
      - Diagrams: pages/api-docs/diagrams.md
  - Development:
      # - pages/dev/README.md
      - Test: pages/dev/test.md
      - Build: pages/dev/build.md
      - Docs: pages/dev/docs.md
      - CI/CD: pages/dev/cicd.md
      - Scripts:
          - pages/dev/scripts/README.md
          - base.sh: pages/dev/scripts/1.base.md
          - clean.sh: pages/dev/scripts/2.clean.md
          - get-version.sh: pages/dev/scripts/3.get-version.md
          - test.sh: pages/dev/scripts/4.test.md
          - bump-version.sh: pages/dev/scripts/5.bump-version.md
          - build.sh: pages/dev/scripts/6.build.md
          - changelog.sh: pages/dev/scripts/7.changelog.md
          - docs.sh: pages/dev/scripts/8.docs.md
          - diagrams.sh: pages/dev/scripts/9.diagrams.md
      - File stucture: pages/dev/file-structure.md
      - Sitemap: pages/dev/sitemap.md
      - Related projects: pages/dev/related-projects.md
      - Contributing: pages/dev/contributing.md
      - Roadmap: pages/dev/roadmap.md
  - Research:
      # - pages/research/README.md
      - Reports: pages/research/reports.md
      - Benchmarks: pages/research/benchmarks.md
      - References: pages/research/references.md
  - Release notes: pages/release-notes.md
  - Blog:
      - pages/blog/index.md
  - About:
      # - pages/about/README.md
      - FAQ: pages/about/faq.md
      - Authors: pages/about/authors.md
      - Contact: pages/about/contact.md
      - License: pages/about/license.md
