version: "3.8"

services:
  api:
    image: bybatkhuu/fastapi-template:latest-gpu
    runtime: nvidia
    env_file:
      - .env
    environment:
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
      CUDA_VISIBLE_DEVICES: ${CUDA_VISIBLE_DEVICES:-all}
    volumes:
      - "./volumes/storage/fastapi-template/logs:${FASTAPI_TEMPLATE_APP_LOGS_DIR:-/var/log/fastapi-template}"
      - "./volumes/storage/fastapi-template/data:${FASTAPI_TEMPLATE_APP_DATA_DIR:-/var/lib/fastapi-template}"
      - "./scripts/docker/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - "./app:/app/fastapi-template"
      - "./volumes/.vscode-server:/home/ft-user/.vscode-server"
    # deploy:
    #   replicas: 0
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M
    # command: ["/bin/bash"]
    # command: ["-b", "sleep 1 && uvicorn main:app --host=0.0.0.0 --port=${FASTAPI_TEMPLATE_APP_PORT:-8000} --no-server-header --proxy-headers --forwarded-allow-ips='*' --no-access-log --reload --reload-include='*.yml' --reload-include='*.yaml' --reload-include='*.json'"]
