api:
  security:
    allowed_hosts: ["*"]
    forwarded_allow_ips: ["*"]
    cors:
      allow_origins: ["*"]
      allow_origin_regex: null
      allow_headers: ["*"]
      allow_methods:
        ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS", "CONNECT"]
      allow_credentials: false
      expose_headers: []
      max_age: 600 # Seconds (10 minutes)
    password:
      pepper: "FT_PASSWORD_PEPPER123" # This should be a random string, and read from an environment variable!
      min_length: 8
      max_length: 128
    asymmetric:
      generate: true
      algorithm: "RS256"
      key_size: 2048
      private_key_fname: "private_key.pem"
      public_key_fname: "public_key.pem"
    jwt:
      secret: "FT_JWT_SECRET123" # This should be a random string, and read from an environment variable!
      algorithm: "HS256"
