api:
  paths:
    tmp_dir: "../tmp"
    uploads_dir: "{tmp_dir}/uploads"
    data_dir: "../data"
    security_dir: "{data_dir}/security"
    asymmetric_keys_dir: "{data_dir}/security/asymmetric_keys"
    # models_dir: "{data_dir}/models"
    # model_dir: "{data_dir}/models/{% raw %}{{model_id}}{% endraw %}"
